# Site settings
title: Sankalp Lakhina | Front End Web Developer
email: sankalp.lakhina91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sankalp Lakhina is a Front End Engineer from New Delhi, India who focuses
  on writing clean, elegant and efficient code. He enjoys turning complex
  problems into simple, beautiful and intuitive interface designs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sankalplakhina.com" # the base hostname & protocol for your site
github_username: sankalplakhina

# Build settings
markdown: kramdown
